#!/bin/bash
python3 -c "WATER_CHARS='water' STIR_CHARS='stir.' BESTCHOL_CHARS='bestchol' print(''.join(BESTCHOL_CHARS[int((int(os.environ['WATER'].translate(str.maketrans(WATER_CHARS,'01234')) if 'water' else '0'),5) + int(os.environ['STIR'].translate(str.maketrans(STIR_CHARS,'012345')) if 'stir.' else '0'),6))//(6**i)%6] for i in range(len('bestchol')))[::-1]).lstrip('b') or BESTCHOL_CHARS[0])"
